/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tg.biblioteck.vues.client;

import tg.biblioteck.modeles.Biblioteck;
import tg.biblioteck.vues.Login;

/**
 *
 * @author fidi
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form client
     */
    public Client() {
        initComponents();
        setTitle("Client");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        desktop_pane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        listeLivres_menu = new javax.swing.JMenuItem();
        mes_emprunts_menu = new javax.swing.JMenuItem();
        reserver_livres_menu = new javax.swing.JMenuItem();
        deconnexion_menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        setName("main_frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 760));
        setSize(new java.awt.Dimension(746, 334));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        desktop_pane.setMinimumSize(new java.awt.Dimension(746, 334));
        desktop_pane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Menu");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        listeLivres_menu.setText("Liste des livres");
        listeLivres_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeLivres_menuMouseClicked(evt);
            }
        });
        listeLivres_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeLivres_menuActionPerformed(evt);
            }
        });
        jMenu1.add(listeLivres_menu);

        mes_emprunts_menu.setText("Mes Emprunts");
        mes_emprunts_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes_emprunts_menuActionPerformed(evt);
            }
        });
        jMenu1.add(mes_emprunts_menu);

        reserver_livres_menu.setText("Réserver Livres");
        reserver_livres_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserver_livres_menuActionPerformed(evt);
            }
        });
        jMenu1.add(reserver_livres_menu);

        deconnexion_menu.setText("Déconnexion");
        deconnexion_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexion_menuActionPerformed(evt);
            }
        });
        jMenu1.add(deconnexion_menu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mes_emprunts_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes_emprunts_menuActionPerformed
        Mes_Emprunts me = new Mes_Emprunts();
        this.desktop_pane.add(me);
        me.setVisible(true);
    }//GEN-LAST:event_mes_emprunts_menuActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

    }//GEN-LAST:event_jMenu1MouseClicked

    private void listeLivres_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeLivres_menuMouseClicked

    }//GEN-LAST:event_listeLivres_menuMouseClicked

    private void listeLivres_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeLivres_menuActionPerformed
        Liste_Livres ll = new Liste_Livres();
        this.desktop_pane.add(ll);
        ll.setVisible(true);
    }//GEN-LAST:event_listeLivres_menuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void deconnexion_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexion_menuActionPerformed
        Biblioteck.logout();
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_deconnexion_menuActionPerformed

    private void reserver_livres_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserver_livres_menuActionPerformed
        Reservation r = new Reservation();
        this.desktop_pane.add(r);
        r.setVisible(true);
    }//GEN-LAST:event_reserver_livres_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem deconnexion_menu;
    private javax.swing.JDesktopPane desktop_pane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem listeLivres_menu;
    private javax.swing.JMenuItem mes_emprunts_menu;
    private javax.swing.JMenuItem reserver_livres_menu;
    // End of variables declaration//GEN-END:variables
}
